name = "koraalenviajeugd"
main = "src/index.ts"
compatibility_date = "2026-06-12"

[assets]
directory = "./public"
binding = "ASSETS"

[observability]
enabled = true

[[d1_databases]]
binding = "OCAI_DB"
database_name = "ocai"
database_id = "4877440a-449f-4e87-a04e-a1c0b7c5ca02"
